In [1]:
import pandas as pd
import numpy as np
import json
import numpy as np
from imdb import IMDb

In [2]:
movies = pd.read_csv("ml-latest-small/linked_movies.csv")

In [3]:
ratings = pd.read_csv("ml-latest-small/ratings.csv")

In [4]:
movie_genre = pd.DataFrame()
movie_language = pd.DataFrame()

In [5]:
for i in range(0,len(movies)):
    movie =  movies.loc[i]
    movie_id = movie['movieId']
    genres = movie['genres'].split('|')
    df = pd.DataFrame({movie_id:np.ones(len(genres))}, index = genres)
    movie_genre = pd.concat([movie_genre, df], axis=1, sort=False)

In [6]:
ia = IMDb()

In [7]:
top250 = ia.get_top250_movies()

In [8]:
top250_movies = {}
for movie in top250:
    top250_movies[int(movie.getID())] = movie.data['rating']

In [9]:
top250_movies = pd.DataFrame.from_dict(top250_movies, orient='index', columns=['imdb_rating'])

In [10]:
top250_movies_ratings = top250_movies['imdb_rating'].values

In [11]:
links = pd.read_csv("ml-latest-small/links.csv")

In [12]:
top250_movies

         imdb_rating
111161           9.2
68646            9.2
71562            9.0
468569           9.0
50083            8.9
108052           8.9
167260           8.9
110912           8.9
60196            8.8
137523           8.8
120737           8.8
109830           8.7
80684            8.7
1375666          8.7
167261           8.7
73486            8.7
99685            8.7
133093           8.6
47478            8.6
317248           8.6
114369           8.6
76759            8.6
102926           8.6
38650            8.6
118799           8.6
114814           8.5
245429           8.5
120815           8.5
110413           8.5
120689           8.5
...              ...
33870            8.0
246578           8.0
97165            8.0
46911            8.0
88247            8.0
83987            8.0
113247           8.0
107048           8.0
32138            8.0
50783            8.0
73195            8.0
56443            8.0
1454029          8.0
118694           8.0
1856101          8.0
3783958          8.0
4016934          8.0
70510            8.0
381681           8.0
2991224          8.0
87884            8.0
1954470          8.0
36868            8.0
92067            8.0
325980           8.0
2015381          8.0
440963           8.0
56801            8.0
1517451          8.0
94625            8.0

[250 rows x 1 columns]

In [13]:
from top250_imdb import Content
model = Content(ratings, movie_genre, top250_movies, links, movies)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35

Z:\Nikhil\IntrotoDS\small\Project\top250_imdb.py:22: RuntimeWarning: invalid value encountered in true_divide
  return (data-min(data))/(max(data) - min(data))

36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610

In [15]:
recs = model.recommendations

In [18]:
with open('recommendations/top250_imdb/top250_imdb.json', 'w') as json_file:
    json.dump(recs, json_file)